# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cliente.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ClienteWindow(object):
    def setupUi(self, ClienteWindow):
        ClienteWindow.setObjectName("ClienteWindow")
        ClienteWindow.resize(366, 238)
        self.verticalLayoutWidget = QtWidgets.QWidget(ClienteWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 30, 291, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.btn_consultar_stock = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_consultar_stock.setObjectName("btn_consultar_stock")
        self.verticalLayout.addWidget(self.btn_consultar_stock)
        self.btn_consultar_precios = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_consultar_precios.setObjectName("btn_consultar_precios")
        self.verticalLayout.addWidget(self.btn_consultar_precios)
        self.btn_volver = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_volver.setObjectName("btn_volver")
        self.verticalLayout.addWidget(self.btn_volver)
        self.btn_salir = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_salir.setObjectName("btn_salir")
        self.verticalLayout.addWidget(self.btn_salir)

        self.retranslateUi(ClienteWindow)
        QtCore.QMetaObject.connectSlotsByName(ClienteWindow)

    def retranslateUi(self, ClienteWindow):
        _translate = QtCore.QCoreApplication.translate
        ClienteWindow.setWindowTitle(_translate("ClienteWindow", "Dialog"))
        self.label.setText(_translate("ClienteWindow", "Panel Cliente"))
        self.btn_consultar_stock.setText(_translate("ClienteWindow", "Consultar Stock"))
        self.btn_consultar_precios.setText(_translate("ClienteWindow", "Consultar Precios"))
        self.btn_volver.setText(_translate("ClienteWindow", "Volver"))
        self.btn_salir.setText(_translate("ClienteWindow", "Salir"))
