# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'consultar_precios.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConsultarPreciosWindow(object):
    def setupUi(self, ConsultarPreciosWindow):
        ConsultarPreciosWindow.setObjectName("ConsultarPreciosWindow")
        ConsultarPreciosWindow.resize(600, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(ConsultarPreciosWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_titulo = QtWidgets.QLabel(ConsultarPreciosWindow)
        self.label_titulo.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_titulo.setFont(font)
        self.label_titulo.setObjectName("label_titulo")
        self.verticalLayout.addWidget(self.label_titulo)
        self.tabla_precios = QtWidgets.QTableWidget(ConsultarPreciosWindow)
        self.tabla_precios.setObjectName("tabla_precios")
        self.tabla_precios.setColumnCount(0)
        self.tabla_precios.setRowCount(0)
        self.verticalLayout.addWidget(self.tabla_precios)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_volver = QtWidgets.QPushButton(ConsultarPreciosWindow)
        self.btn_volver.setObjectName("btn_volver")
        self.horizontalLayout.addWidget(self.btn_volver)
        self.btn_salir = QtWidgets.QPushButton(ConsultarPreciosWindow)
        self.btn_salir.setObjectName("btn_salir")
        self.horizontalLayout.addWidget(self.btn_salir)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(ConsultarPreciosWindow)
        QtCore.QMetaObject.connectSlotsByName(ConsultarPreciosWindow)

    def retranslateUi(self, ConsultarPreciosWindow):
        _translate = QtCore.QCoreApplication.translate
        ConsultarPreciosWindow.setWindowTitle(_translate("ConsultarPreciosWindow", "Consultar Precios"))
        self.label_titulo.setText(_translate("ConsultarPreciosWindow", "Precios de Productos"))
        self.btn_volver.setText(_translate("ConsultarPreciosWindow", "Volver"))
        self.btn_salir.setText(_translate("ConsultarPreciosWindow", "Salir"))
