# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'consultar_stock.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConsultarStockWindow(object):
    def setupUi(self, ConsultarStockWindow):
        ConsultarStockWindow.setObjectName("ConsultarStockWindow")
        ConsultarStockWindow.resize(600, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(ConsultarStockWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_titulo = QtWidgets.QLabel(ConsultarStockWindow)
        self.label_titulo.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_titulo.setFont(font)
        self.label_titulo.setObjectName("label_titulo")
        self.verticalLayout.addWidget(self.label_titulo)
        self.tabla_stock = QtWidgets.QTableWidget(ConsultarStockWindow)
        self.tabla_stock.setObjectName("tabla_stock")
        self.tabla_stock.setColumnCount(0)
        self.tabla_stock.setRowCount(0)
        self.verticalLayout.addWidget(self.tabla_stock)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_volver = QtWidgets.QPushButton(ConsultarStockWindow)
        self.btn_volver.setObjectName("btn_volver")
        self.horizontalLayout.addWidget(self.btn_volver)
        self.btn_salir = QtWidgets.QPushButton(ConsultarStockWindow)
        self.btn_salir.setObjectName("btn_salir")
        self.horizontalLayout.addWidget(self.btn_salir)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(ConsultarStockWindow)
        QtCore.QMetaObject.connectSlotsByName(ConsultarStockWindow)

    def retranslateUi(self, ConsultarStockWindow):
        _translate = QtCore.QCoreApplication.translate
        ConsultarStockWindow.setWindowTitle(_translate("ConsultarStockWindow", "Consultar Stock"))
        self.label_titulo.setText(_translate("ConsultarStockWindow", "Productos en Stock"))
        self.btn_volver.setText(_translate("ConsultarStockWindow", "Volver"))
        self.btn_salir.setText(_translate("ConsultarStockWindow", "Salir"))
