# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jefe_valor_stock.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VentanaJefe(object):
    def setupUi(self, VentanaJefe):
        VentanaJefe.setObjectName("VentanaJefe")
        VentanaJefe.resize(400, 200)
        self.verticalLayout = QtWidgets.QVBoxLayout(VentanaJefe)
        self.verticalLayout.setObjectName("verticalLayout")
        self.boton_valor_stock = QtWidgets.QPushButton(VentanaJefe)
        self.boton_valor_stock.setObjectName("boton_valor_stock")
        self.verticalLayout.addWidget(self.boton_valor_stock)
        self.label_valor_stock = QtWidgets.QLabel(VentanaJefe)
        self.label_valor_stock.setAlignment(QtCore.Qt.AlignCenter)
        self.label_valor_stock.setWordWrap(True)
        self.label_valor_stock.setMinimumSize(QtCore.QSize(0, 40))
        self.label_valor_stock.setObjectName("label_valor_stock")
        self.verticalLayout.addWidget(self.label_valor_stock)

        self.retranslateUi(VentanaJefe)
        QtCore.QMetaObject.connectSlotsByName(VentanaJefe)

    def retranslateUi(self, VentanaJefe):
        _translate = QtCore.QCoreApplication.translate
        VentanaJefe.setWindowTitle(_translate("VentanaJefe", "Panel Jefe - Valor Stock"))
        self.boton_valor_stock.setText(_translate("VentanaJefe", "Calcular valor total del stock"))
        self.label_valor_stock.setText(_translate("VentanaJefe", "Valor total del stock: "))
