# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_label_usuario(object):
    def setupUi(self, label_usuario):
        label_usuario.setObjectName("label_usuario")
        label_usuario.resize(696, 426)
        self.groupBox = QtWidgets.QGroupBox(label_usuario)
        self.groupBox.setGeometry(QtCore.QRect(90, 50, 351, 291))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.line_usuario = QtWidgets.QLineEdit(self.groupBox)
        self.line_usuario.setObjectName("line_usuario")
        self.verticalLayout_2.addWidget(self.line_usuario)
        self.label_contrasena = QtWidgets.QLabel(self.groupBox)
        self.label_contrasena.setObjectName("label_contrasena")
        self.verticalLayout_2.addWidget(self.label_contrasena)
        self.line_contrasena = QtWidgets.QLineEdit(self.groupBox)
        self.line_contrasena.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_contrasena.setObjectName("line_contrasena")
        self.verticalLayout_2.addWidget(self.line_contrasena)
        self.label_rol = QtWidgets.QLabel(self.groupBox)
        self.label_rol.setObjectName("label_rol")
        self.verticalLayout_2.addWidget(self.label_rol)
        self.combo_rol = QtWidgets.QComboBox(self.groupBox)
        self.combo_rol.setEditable(False)
        self.combo_rol.setObjectName("combo_rol")
        self.combo_rol.addItem("")
        self.combo_rol.addItem("")
        self.combo_rol.addItem("")
        self.verticalLayout_2.addWidget(self.combo_rol)
        self.btn_login = QtWidgets.QPushButton(self.groupBox)
        self.btn_login.setObjectName("btn_login")
        self.verticalLayout_2.addWidget(self.btn_login)
        self.btn_registrar = QtWidgets.QPushButton(self.groupBox)
        self.btn_registrar.setObjectName("btn_registrar")
        self.verticalLayout_2.addWidget(self.btn_registrar)
        self.btn_salir = QtWidgets.QPushButton(self.groupBox)
        self.btn_salir.setObjectName("btn_salir")
        self.verticalLayout_2.addWidget(self.btn_salir)
        self.label_error = QtWidgets.QLabel(self.groupBox)
        self.label_error.setObjectName("label_error")
        self.verticalLayout_2.addWidget(self.label_error)

        self.retranslateUi(label_usuario)
        QtCore.QMetaObject.connectSlotsByName(label_usuario)

    def retranslateUi(self, label_usuario):
        _translate = QtCore.QCoreApplication.translate
        label_usuario.setWindowTitle(_translate("label_usuario", "Dialog"))
        self.groupBox.setTitle(_translate("label_usuario", "SuperControl"))
        self.label.setText(_translate("label_usuario", "Usuario"))
        self.label_contrasena.setText(_translate("label_usuario", "Contraseña"))
        self.label_rol.setText(_translate("label_usuario", "Rol"))
        self.combo_rol.setItemText(0, _translate("label_usuario", "Cliente"))
        self.combo_rol.setItemText(1, _translate("label_usuario", "Empleado"))
        self.combo_rol.setItemText(2, _translate("label_usuario", "Jefe"))
        self.btn_login.setText(_translate("label_usuario", "Iniciar Sesión"))
        self.btn_registrar.setText(_translate("label_usuario", "Registrarse"))
        self.btn_salir.setText(_translate("label_usuario", "Salir"))
        self.label_error.setText(_translate("label_usuario", "error"))
