# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eliminar_producto.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EliminarProductoWindow(object):
    def setupUi(self, EliminarProductoWindow):
        EliminarProductoWindow.setObjectName("EliminarProductoWindow")
        self.verticalLayout = QtWidgets.QVBoxLayout(EliminarProductoWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_titulo = QtWidgets.QLabel(EliminarProductoWindow)
        self.label_titulo.setObjectName("label_titulo")
        self.verticalLayout.addWidget(self.label_titulo)
        self.combo_productos = QtWidgets.QComboBox(EliminarProductoWindow)
        self.combo_productos.setObjectName("combo_productos")
        self.verticalLayout.addWidget(self.combo_productos)
        self.btn_eliminar = QtWidgets.QPushButton(EliminarProductoWindow)
        self.btn_eliminar.setObjectName("btn_eliminar")
        self.verticalLayout.addWidget(self.btn_eliminar)
        self.btn_volver = QtWidgets.QPushButton(EliminarProductoWindow)
        self.btn_volver.setObjectName("btn_volver")
        self.verticalLayout.addWidget(self.btn_volver)

        self.retranslateUi(EliminarProductoWindow)
        QtCore.QMetaObject.connectSlotsByName(EliminarProductoWindow)

    def retranslateUi(self, EliminarProductoWindow):
        _translate = QtCore.QCoreApplication.translate
        EliminarProductoWindow.setWindowTitle(_translate("EliminarProductoWindow", "Eliminar Producto"))
        self.label_titulo.setText(_translate("EliminarProductoWindow", "Selecciona un producto para eliminar:"))
        self.btn_eliminar.setText(_translate("EliminarProductoWindow", "Eliminar"))
        self.btn_volver.setText(_translate("EliminarProductoWindow", "Volver"))