# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'empleado.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EmpleadoWindow(object):
    def setupUi(self, EmpleadoWindow):
        EmpleadoWindow.setObjectName("EmpleadoWindow")
        EmpleadoWindow.resize(366, 225)
        self.verticalLayoutWidget = QtWidgets.QWidget(EmpleadoWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 30, 291, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.btn_modificar_stock = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_modificar_stock.setObjectName("btn_modificar_stock")
        self.verticalLayout.addWidget(self.btn_modificar_stock)
        self.btn_anadir_producto = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_anadir_producto.setObjectName("btn_aniadir_producto")
        self.verticalLayout.addWidget(self.btn_anadir_producto)
        self.btn_volver = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_volver.setObjectName("btn_volver")
        self.verticalLayout.addWidget(self.btn_volver)
        self.btn_salir = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_salir.setObjectName("btn_salir")
        self.verticalLayout.addWidget(self.btn_salir)

        self.retranslateUi(EmpleadoWindow)
        QtCore.QMetaObject.connectSlotsByName(EmpleadoWindow)

    def retranslateUi(self, EmpleadoWindow):
        _translate = QtCore.QCoreApplication.translate
        EmpleadoWindow.setWindowTitle(_translate("EmpleadoWindow", "Dialog"))
        self.label.setText(_translate("EmpleadoWindow", "Panel Empleado"))
        self.btn_modificar_stock.setText(_translate("EmpleadoWindow", "Modificar Stock"))
        self.btn_anadir_producto.setText(_translate("EmpleadoWindow", "Añadir nuevo producto"))
        self.btn_volver.setText(_translate("EmpleadoWindow", "Volver"))
        self.btn_salir.setText(_translate("EmpleadoWindow", "Salir"))
