# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'informe_stock.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InformeStockWindow(object):
    def setupUi(self, InformeStockWindow):
        InformeStockWindow.setObjectName("InformeStockWindow")
        InformeStockWindow.resize(519, 286)
        self.verticalLayout = QtWidgets.QVBoxLayout(InformeStockWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_titulo = QtWidgets.QLabel(InformeStockWindow)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_titulo.setFont(font)
        self.label_titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titulo.setObjectName("label_titulo")
        self.verticalLayout.addWidget(self.label_titulo)
        self.tabla_stock = QtWidgets.QTableWidget(InformeStockWindow)
        self.tabla_stock.setRowCount(0)
        self.tabla_stock.setColumnCount(4)
        self.tabla_stock.setObjectName("tabla_stock")
        self.verticalLayout.addWidget(self.tabla_stock)
        self.horizontalLayout_botones = QtWidgets.QHBoxLayout()
        self.horizontalLayout_botones.setObjectName("horizontalLayout_botones")
        self.btn_exportar = QtWidgets.QPushButton(InformeStockWindow)
        self.btn_exportar.setObjectName("btn_exportar")
        self.horizontalLayout_botones.addWidget(self.btn_exportar)
        self.btn_cerrar = QtWidgets.QPushButton(InformeStockWindow)
        self.btn_cerrar.setObjectName("btn_cerrar")
        self.horizontalLayout_botones.addWidget(self.btn_cerrar)
        self.verticalLayout.addLayout(self.horizontalLayout_botones)

        self.retranslateUi(InformeStockWindow)
        QtCore.QMetaObject.connectSlotsByName(InformeStockWindow)

    def retranslateUi(self, InformeStockWindow):
        _translate = QtCore.QCoreApplication.translate
        InformeStockWindow.setWindowTitle(_translate("InformeStockWindow", "Informe de Stock"))
        self.label_titulo.setText(_translate("InformeStockWindow", "Informe de Productos"))
        self.btn_exportar.setText(_translate("InformeStockWindow", "Exportar CSV"))
        self.btn_cerrar.setText(_translate("InformeStockWindow", "Cerrar"))
