# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jefe.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JefeWindow(object):
    def setupUi(self, JefeWindow):
        JefeWindow.setObjectName("JefeWindow")
        JefeWindow.resize(366, 238)
        self.verticalLayoutWidget = QtWidgets.QWidget(JefeWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 30, 291, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.btn_generar_informe_stock = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_generar_informe_stock.setObjectName("btn_generar_informe_stock")
        self.verticalLayout.addWidget(self.btn_generar_informe_stock)
        self.btn_modificar_precio = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_modificar_precio.setObjectName("btn_modificar_precio")
        self.verticalLayout.addWidget(self.btn_modificar_precio)
        self.btn_calcular_valor_stock = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_calcular_valor_stock.setObjectName("btn_calcular_valor_stock")
        self.verticalLayout.addWidget(self.btn_calcular_valor_stock)
        self.btn_volver = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_volver.setObjectName("btn_volver")
        self.verticalLayout.addWidget(self.btn_volver)
        self.btn_salir = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_salir.setObjectName("btn_salir")
        self.verticalLayout.addWidget(self.btn_salir)

        self.retranslateUi(JefeWindow)
        QtCore.QMetaObject.connectSlotsByName(JefeWindow)

    def retranslateUi(self, JefeWindow):
        _translate = QtCore.QCoreApplication.translate
        JefeWindow.setWindowTitle(_translate("JefeWindow", "Dialog"))
        self.label.setText(_translate("JefeWindow", "Panel Jefe"))
        self.btn_generar_informe_stock.setText(_translate("JefeWindow", "Generar Informe Stock"))
        self.btn_modificar_precio.setText(_translate("JefeWindow", "Modificar Precio Producto"))
        self.btn_calcular_valor_stock.setText(_translate("JefeWindow", "Calcular Valor Total del Stock"))
        self.btn_volver.setText(_translate("JefeWindow", "Volver"))
        self.btn_salir.setText(_translate("JefeWindow", "Salir"))
