# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modificar_precio.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ModificarPrecioWindow(object):
    def setupUi(self, ModificarPrecioWindow):
        ModificarPrecioWindow.setObjectName("ModificarPrecioWindow")
        ModificarPrecioWindow.resize(600, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(ModificarPrecioWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_titulo = QtWidgets.QLabel(ModificarPrecioWindow)
        self.label_titulo.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_titulo.setFont(font)
        self.label_titulo.setObjectName("label_titulo")
        self.verticalLayout.addWidget(self.label_titulo)
        self.tabla_precios = QtWidgets.QTableWidget(ModificarPrecioWindow)
        self.tabla_precios.setObjectName("tabla_precios")
        self.tabla_precios.setColumnCount(0)
        self.tabla_precios.setRowCount(0)
        self.verticalLayout.addWidget(self.tabla_precios)
        self.horizontalLayout_inputs = QtWidgets.QHBoxLayout()
        self.horizontalLayout_inputs.setObjectName("horizontalLayout_inputs")
        self.label_nuevo_precio = QtWidgets.QLabel(ModificarPrecioWindow)
        self.label_nuevo_precio.setObjectName("label_nuevo_precio")
        self.horizontalLayout_inputs.addWidget(self.label_nuevo_precio)
        self.line_nuevo_precio = QtWidgets.QLineEdit(ModificarPrecioWindow)
        self.line_nuevo_precio.setObjectName("line_nuevo_precio")
        self.horizontalLayout_inputs.addWidget(self.line_nuevo_precio)
        self.btn_actualizar = QtWidgets.QPushButton(ModificarPrecioWindow)
        self.btn_actualizar.setObjectName("btn_actualizar")
        self.horizontalLayout_inputs.addWidget(self.btn_actualizar)
        self.verticalLayout.addLayout(self.horizontalLayout_inputs)
        self.horizontalLayout_botones = QtWidgets.QHBoxLayout()
        self.horizontalLayout_botones.setObjectName("horizontalLayout_botones")
        self.btn_volver = QtWidgets.QPushButton(ModificarPrecioWindow)
        self.btn_volver.setObjectName("btn_volver")
        self.horizontalLayout_botones.addWidget(self.btn_volver)
        self.btn_salir = QtWidgets.QPushButton(ModificarPrecioWindow)
        self.btn_salir.setObjectName("btn_salir")
        self.horizontalLayout_botones.addWidget(self.btn_salir)
        self.verticalLayout.addLayout(self.horizontalLayout_botones)

        self.retranslateUi(ModificarPrecioWindow)
        QtCore.QMetaObject.connectSlotsByName(ModificarPrecioWindow)

    def retranslateUi(self, ModificarPrecioWindow):
        _translate = QtCore.QCoreApplication.translate
        ModificarPrecioWindow.setWindowTitle(_translate("ModificarPrecioWindow", "Modificar Precio"))
        self.label_titulo.setText(_translate("ModificarPrecioWindow", "Modificar Precio de Producto"))
        self.label_nuevo_precio.setText(_translate("ModificarPrecioWindow", "Nuevo Precio:"))
        self.btn_actualizar.setText(_translate("ModificarPrecioWindow", "Actualizar Precio"))
        self.btn_volver.setText(_translate("ModificarPrecioWindow", "Volver"))
        self.btn_salir.setText(_translate("ModificarPrecioWindow", "Salir"))
